name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.17.6<=3.0.0'
#  flutter: '>=2.5.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  #charts_common: ^0.12.0
  charts_common: #图表
    git:
      url: https://github.com/493628242/charts.git
      path: charts_common
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.1.1


dev_dependencies:
  mockito: ^5.3.2
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.21.4
